version: '3'

services:
  nemaki-setup-ui:
    build: ./image
    environment:
      - SCALA_VERSION=2.11.8 
      - nemakiware.version=2.5
    volumes:
      - ./result:/share
    tty: true
    command: /home/scripts/setup.sh